#!/bin/bash
#PBS -N h5bench_native_test
#PBS -l select=1:ncpus=4:mpiprocs=4:mem=2gb
#PBS -l walltime=00:05:00
#PBS -l place=excl
#PBS -q normal
#PBS -P personal-haiyen02
#PBS -j oe
#PBS -o logs/h5bench_native_test.out

cd "$PBS_O_WORKDIR"

module purge
module load libfabric/1.11.0.4.125
module load intel/2022.0.2
module load hdf5/1.12.1-parallel-icc22-ompi4
module swap openmpi/4.1.7-icc24.2.1 openmpi/4.1.2-hpe
module swap intel/2024.2.1 intel/2022.0.2

module list
which mpirun
mpirun --version

mpicc -show
which mpicc
mpicc --version

# MCA parameters to suppress Slingshot/UCX warnings
# export OMPI_MCA_btl="^openib"
# export OMPI_MCA_opal_common_ucx_opal_mem_hooks=1

H5BENCH_BIN=$HOME/scratch/fyp/native/h5bench/h5bench/build/install/bin/h5bench

# Pin Lustre striping explicitly 
OUTPUT_DIR="h5bench_native_output"
mkdir -p "$OUTPUT_DIR"
lfs setstripe -c 4 -S 1m "$OUTPUT_DIR"
echo "=== Verifying Lustre striping layout for $OUTPUT_DIR ==="
lfs getstripe "$OUTPUT_DIR"

# Execute h5bench with corrected JSON
${H5BENCH_BIN} native_sample_write_read.json --debug

# Move h5bench log to logs/ 
mv native_sample_write_read-h5bench.log logs/
